spreading_model:
  name: "TorchMICModel"
  parameters:
    protocols: ["OR"]
    p_values: [0.05, 0.10, 0.15, 0.20]
  # parameters:
  #   protocols: ["AND"]
  #   p_values: [0.80, 0.85, 0.90, 0.95]

networks: [
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### train/eval split
  # "artificial_er-*",
  # "artificial_pa-*",
  "artificial_small-*",
  # # ##### ##### ##### ##### ##### ##### ##### ##### ##### test split
  # "arxiv_netscience_coauthorship-arxiv_netscience_coauthorship",
  # "aucs",
  # "ckm_physicians",
  # "eu_transportation-eu_transportation",
  "l2_course-l2_course_net_1",
  # "lazega",
  # "timik1q2009",
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### not used at all
  # "arxiv_netscience_coauthorship-arxiv_netscience_coauthorship_math.oc",
  # "cannes",
  # "eu_transportation-eu_transport_klm",
  # "fmri74",
  # "toy_network",
]

infmax_models:
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### centrality based
  - name: "degree"
    class: "CachedCentralityChoice"
    parameters:
      nb_seeds: "auto"
      centrality: "degree"
  - name: "betweenness"
    class: "CachedCentralityChoice"
    parameters:
      nb_seeds: "auto"
      centrality: "betweenness"
  - name: "closeness"
    class: "CachedCentralityChoice"
    parameters:
      nb_seeds: "auto"
      centrality: "closeness"
  - name: "core_number"
    class: "CachedCentralityChoice"
    parameters:
      nb_seeds: "auto"
      centrality: "core_number"
  - name: "neighbourhood_size"
    class: "CachedCentralityChoice"
    parameters:
      nb_seeds: "auto"
      centrality: "neighbourhood_size"
  - name: "voterank"
    class: "CachedCentralityChoice"
    parameters:
      nb_seeds: "auto"
      centrality: "voterank"
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### ground truth
  - name: "gt_absoulute"
    class: "GroundTruth"
    parameters:
      average_protocol: False
      average_p_value: False
  - name: "gt_avg_p"
    class: "GroundTruth"
    parameters:
      average_protocol: False
      average_p_value: True
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### random
  - name: "random_choice"
    class: "RandomChoice"
    nb_seeds: "auto"
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### df choice
  - name: "ssnet"
    class: "DFChoice"
    parameters:
      result_dir: ""
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### GBIM
  - name: "gbim"
    class: "GBIM"
    parameters:
      rng_seed: auto
      device: auto
      common:
        nb_seeds: auto
        graphsample: 1000
      datasample:
        sample_num: 1000
        simulate_times: 10
      executor:
        epochs: 300
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### deepim
  - name: "deep_im"
    class: "DeepIM"
    parameters:
      rng_seed: auto
      device: auto
      seeding_budget: 5
      common:
        nb_pred_actos: auto
        nb_pred_nodes: 4
      executor:
        train_epochs: 600
        y_hat_epochs: 300
        patience: 5
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### multi-node2vec-k-means
  - name: "mn2v_km"
    class: "MultiNode2VecKMeansAuto"
    parameters:
      rng_seed: "auto"
      multi_node2vec:
        d: "auto"
        window_size: 10
        n_samples: 1
        thresh: 0.5
        pvals: 1
        qvals: 0.5
        rvals: 0.25
      k_means:
        nb_seeds: "auto"
        max_nb_clusters: "auto"
        centrality_criterium: "centroid"
        experiment_name: ""
        visualise: False

run:
  experiment_type: "evaluate"
  nb_diffusion_seeds: 1
  nb_repetitions:
    diffusion: 30
    stochastic_infmax: 30
  rng_seed: 43
  average_results: False
  device: cpu

logging:
  compress_to_zip: False
  out_dir: "example_results/evaluator"
