run:
  experiment_type: "regression"
  rng_seed: 43
  nb_repetitions: 30

logging:
  out_dir: "data/regression"

spreading_model:
  parameters:
    protocols: ["OR", "AND"]
    p_values: [-1]  # OR [0.05, 0.10, 0.15, 0.20], AND [0.80, 0.85, 0.90, 0.95]

networks: [
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### train/eval split
  # "artificial_er-network_15",
  # "artificial_er-network_20",
  # "artificial_er-network_40",
  # "artificial_er-network_45",
  # "artificial_er-network_71",
  # "artificial_er-network_78",
  # "artificial_er-network_79",
  # "artificial_er-network_80",
  # "artificial_pa-network_7",
  # "artificial_pa-network_23",
  # "artificial_pa-network_39",
  # "artificial_pa-network_57",
  # "artificial_pa-network_58",
  # "artificial_pa-network_75",
  # "artificial_pa-network_85",
  # "artificial_pa-network_95",
  # "artificial_pa-network_22",  # it was in test split but is not used in eval
  # "artificial_pa-network_68",  # to balance pa/er
  # "artificial_pa-network_83",  # ditto
  # "artificial_pa-network_93",  # ditto
  # "artificial_er-*",
  # "artificial_pa-*",
  # "artificial_small-*",
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### test split
  # "arxiv_netscience_coauthorship-arxiv_netscience_coauthorship",
  "aucs",
  # "ckm_physicians",
  # "eu_transportation-eu_transportation",
  # "l2_course-l2_course_net_1",
  # "lazega",
  # "timik1q2009",
  # ##### ##### ##### ##### ##### ##### ##### ##### ##### not used at all
  # "arxiv_netscience_coauthorship-arxiv_netscience_coauthorship_math.oc",
  # "cannes",
  # "eu_transportation-eu_transport_klm",
  # "fmri74",
  # "toy_network",
]

regr_models:
  - name: "deg-c"
    class: "CachedCentralityRegressor"
    parameters:
      centrality_names: ["degree"]
      rng_seed: "auto"
      nb_repetitions: "auto"
  # - name: "btwns"
  #   class: "CachedCentralityRegressor"
  #   parameters:
  #     centrality_names: ["betweenness"]
  #     rng_seed: "auto"
  #     nb_repetitions: "auto"
  # - name: "clsns"
  #   class: "CachedCentralityRegressor"
  #   parameters:
  #     centrality_names: ["closeness"]
  #     rng_seed: "auto"
  #     nb_repetitions: "auto"
  # - name: "k-sh"
  #   class: "CachedCentralityRegressor"
  #   parameters:
  #     centrality_names: ["core_number"]
  #     rng_seed: "auto"
  #     nb_repetitions: "auto"
  # - name: "nghb-s"
  #   class: "CachedCentralityRegressor"
  #   parameters:
  #     centrality_names: ["neighbourhood_size"]
  #     rng_seed: "auto"
  #     nb_repetitions: "auto"
  # - name: "v-rnk-m"
  #   class: "CachedCentralityRegressor"
  #   parameters:
  #     centrality_names: ["voterank"]
  #     rng_seed: "auto"
  #     nb_repetitions: "auto"
  # - name: "dbccnv"
  #   class: "CachedCentralityRegressor"
  #   parameters:
  #     centrality_names: [
  #       "degree",
  #       "betweenness",
  #       "closeness",
  #       "core_number",
  #       "neighbourhood_size",
  #       "voterank",
  #     ]
  #     rng_seed: "auto"
  #     nb_repetitions: "auto"
  - name: "801"
    class: "NeptuneRegressor"
    parameters:
      project: infmax/infmax-gnn
      run: IN-801
  - name: "802"
    class: "NeptuneRegressor"
    parameters:
      project: infmax/infmax-gnn
      run: IN-802
